bolao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # para configurar o caminho da pasta media no raiz do projeto
from django.conf.urls.static import static # idem --> media

urlpatterns = [
    path('', include('bolao_app.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # idem --> media

bolao_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landingpage, name='landingpage'),
    path('login/', views.login, name='login'),
    path('accounts/login/', views.login, name='login'), #para redirecionar quando o usuário fizer logoff no sistema
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    #path('dashboard/shotresult', views.shotresult, name='shotresult'),
    path('dashboard/ranking/', views.ranking, name='ranking'),
    path('dashboard/bets/', views.bets, name='bets'),
    #path('dashboard/bets_result/', views.bets_result, name='bets_result'),
    path('dashboard/add_credit/', views.add_credit, name='add_credit'),
    path('dashboard/admin_register_result/', views.admin_register_result, name='admin_register_result'), # TODO: so mostar esta pagina para usuários que são administradores do site
]

bolao_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from datetime import date, datetime
from django.utils import timezone
from decimal import Decimal

class Apostador(models.Model):
    # Representa um apostador que pode realizar apostas no bolao 
    class Meta:
        verbose_name_plural = "Apostadores"

    usuario = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='apostadorusuario',  # renomei a chave para evitar erros na hora da migracao
    )
    credito = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        default=10.00,
        editable=True,
    )  # não exibe valor da ser ajustado
    premiacao_ganha = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        default=0.00,
        editable=True,
    )  # não exibe valor da ser ajustado

    qtd_vitorias = models.PositiveSmallIntegerField(
        editable=True,
        default=0,
        blank=True,
    )

    def __str__(self):
        # Retorna uma representacao de um apostador
        return "%s" % self.usuario

    def apostar_valor(self, valor=5.00):
        """ Abatate valor da aposta realizada no credito do apostador  """
        self.credito -= Decimal(valor)

    def adicionar_credito(self, credito):
        """ Adiciona credito na conta do apostador  """
        self.credito += Decimal(credito)
        self.save()

class Selecao(models.Model):
    """  """

    class Meta:
        verbose_name_plural = "Seleções"  # Nome que de fato sera exibido no site para a tabela no plural
        ordering = ["nome"]  # odenacao que sera realizada, pode ser mais de um campo (- ordem decrescente)

    # id pk
    nome = models.CharField(
        max_length=200,
    )
    qtd_titulos = models.PositiveSmallIntegerField()

    def __str__(self):
        """  """
        return self.nome


class Partida(models.Model):
    """  """

    # id pk - id_pa = models.IntegerField(primary_key=True)
    class Meta:
        ordering = ["-data_hora_inicio"]

    selecao_desafiante = models.ForeignKey(
        Selecao,
        on_delete=models.CASCADE,
        related_name='selecaodesafiante',
    )
    selecao_visitante = models.ForeignKey(
        Selecao,
        on_delete=models.CASCADE,
        related_name='selecaovisitante',
    )
    gols_desafiante = models.PositiveSmallIntegerField(
        blank=True,
        null=True,
        editable=True,
    )  # não exibe valor da ser ajustado
    gols_visitante = models.PositiveSmallIntegerField(
        blank=True,
        null=True,
        editable=True,
    )  # não exibe valor da ser ajustado
    estadio = models.CharField(
        max_length=200,
    )
    
    data_hora_inicio = models.DateTimeField(
        auto_now=False,
        auto_now_add=False,
    )
    
    data_hora_fim = models.DateTimeField(
        auto_now=False,
        auto_now_add=False,
    )

    finalizada = models.BooleanField(
        default=False,
        editable=True,
    )  # não exibe valor da ser ajustado

    def __str__(self):
        """  """
        return "%s x %s" % (self.selecao_desafiante, self.selecao_visitante)
    
    def finalizar_partida(self):
        if not self.data_hora_fim >= timezone.now(): #datetime.now():
            self.finalizada = True
            self.save()

    def definir_resultado(self, gols_desaf, gols_visit):
        self.gols_desafiante = gols_desaf
        self.gols_visitante = gols_visit
        self.save()


class Bolao(models.Model):
    """  """

    class Meta:
        verbose_name_plural = "Bolões"
        ordering = ["nome"]

    # id pk
    nome = models.CharField(
        max_length=200,
    )
    partida = models.ForeignKey(
        Partida,
        on_delete=models.CASCADE,
    )  # fk
    premiacao = models.FloatField(
        default=0.0,
        editable=True,
    )  # não exibe valor da ser ajustado
    valor_disputado = models.FloatField(
        default=0.0,
        editable=True,
    )  # não exibe valor da ser ajustado
    esta_ativo = models.BooleanField(
        default=True,
        editable=True,
    )  # não exibe valor da ser ajustado
    
    def __str__(self):
        return self.nome

    #TODO: corrigir erro aqui
    def desativar_bolao(self, partida):
        if not partida.data_hora_inicio >= timezone.now(): #datetime.now():
            self.esta_ativo = False
            self.save()

    def adicionar_aposta(self, aposta):
        """ Adiciona aposta ao bolao """
        apostador = Apostador.objects.filter(usuario_id=aposta.apostador_id).first()
        
        if apostador.credito >= aposta.valor: # so permite que a aposta seja efetivada caso o credito do apostador seja maior ou igual ao valor da aposta
            #self.apostas.append(aposta)
            self.valor_disputado += aposta.valor # amplia o valor em disputa do bolao
            apostador.apostar_valor(aposta.valor) # reduz o valor do credito do apostador
            apostador.save() #salva o apostador
            self.save() #salva o bolao
            aposta.save() #salva a aposta
        else:
            raise ValueError("Seu crédito atual é de >> R$ " + str(aposta.apostador.credito) + " << insuficiente para realizar uma aposta!")
    
    def remover_aposta(self, aposta):
        """ Remove uma aposta do bolao """
        #self.apostas.remove(aposta)
        #TODO: colocar aqui o codigo sobre a remocao da aposta
        self.valor_disputado -= aposta.valor_aposta
        aposta.apostador.adicionar_credito(aposta.valor_aposta) # devolve o valor da  aposta no credito do apostador

    def set_premiacao(self, apostadores, vencedores):
        """ Processa e define a premiacao ou nao do bolao, coso nao haja vencedor devolve o credito ao apstador """
        #TODO: fazer um filtro apenas para os vencedores do bolao atual, verificar a pertinencia
        if vencedores: # se a lista nao estiver vazia divide o valor disputado pela quantidade de vencedores seta a premiacao
            self.premiacao = (self.valor_disputado/len(vencedores))
            self.save()
            for ven in vencedores: # distribui a premiacao para os vencedores
                apostador = Apostador.objects.filter(usuario_id=ven.apostador_id).first()
                apostador.premiacao_ganha += Decimal(self.premiacao)
                apostador.qtd_vitorias += 1
                apostador.save()
                apostador.adicionar_credito(self.premiacao) # converte a premiacao em credito
        else: # se nao houver vencedores devolve o credito para o apostador
            for apostador in apostadores: 
                apostador.adicionar_credito(5.00) #depois ajustar

    def verificar_vencedores(self, apostas, vencedores):
        """ Processa e define os vencedores ou nao do bolao  """
        
        # relacao de apostadores no caso de devolucao de valores
        apostadores = []

        for ap in apostas: # verifica quem acertou o bolao pelo resultado identico do placar 
            if ap.bolao.partida.gols_desafiante == ap.qtd_gols_desafiante and ap.bolao.partida.gols_visitante == ap.qtd_gols_visitante:
                # registra o(s) vencedor(es) do baolao
                vencedor = ApostadorVencedorBolao() 
                vencedor.apostador = ap.apostador
                vencedor.bolao = ap.bolao
                vencedor.save()
                vencedores.append(vencedor)

                #TODO: colocar aqui o codigo sobre as insercao de vencedores
                #vencedores.append(ap.apostador)
        
        if not vencedores: # se ninguem tiver acetado o placar verifica quem ACERTOU A VITORIA DO DESAFIANTE
            for ap in apostas:
                if ap.bolao.partida.gols_desafiante > ap.bolao.partida.gols_visitante and ap.qtd_gols_desafiante > ap.qtd_gols_visitante:
                    vencedor = ApostadorVencedorBolao() 
                    vencedor.apostador = ap.apostador
                    vencedor.bolao = ap.bolao
                    vencedor.save()
                    vencedores.append(vencedor)
                    #TODO: colocar aqui o codigo sobre as insercao de vencedores
                    #vencedores.append(ap.apostador)

        if not vencedores: # se ninguem tiver acetado o placar verifica quem ACERTOU A VITORIA DO VISITANTE
            for ap in apostas:
                if ap.bolao.partida.gols_desafiante < ap.bolao.partida.gols_visitante and ap.qtd_gols_desafiante < ap.qtd_gols_visitante:
                    vencedor = ApostadorVencedorBolao() 
                    vencedor.apostador = ap.apostador
                    vencedor.bolao = ap.bolao
                    vencedor.save()
                    vencedores.append(vencedor)
                    #TODO: colocar aqui o codigo sobre as insercao de vencedores
                    #vencedores.append(ap.apostador)

        if not vencedores: # se ninguem tiver acetado o placar verifica quem ACERTOU O EMPATE ENTRE AS SELECOES
            for ap in apostas:
                if ap.bolao.partida.gols_desafiante == ap.bolao.partida.gols_visitante and ap.qtd_gols_desafiante == ap.qtd_gols_visitante:
                    vencedor = ApostadorVencedorBolao() 
                    vencedor.apostador = ap.apostador
                    vencedor.bolao = ap.bolao
                    vencedor.save()
                    vencedores.append(vencedor)
                    #TODO: colocar aqui o codigo sobre as insercao de vencedores
                    #vencedores.append(ap.apostador)
        
        #relaciona todos os apostadores
        for ap in apostas:
            apostador = Apostador()
            apostador = ap.apostador

bolao_app/templates/bolao_app/dashboard.html
<style>
  #container {
      border-radius: 10px;
      background-color: rgba(255, 255, 255, 0.7);
      padding : 20px;
      }

</style>
{% extends 'base.html' %}
{% block  titulo%} Painel de {{ user.first_name }} | {% endblock  %}


{% block conteudo %}

  <!-- Navigation -->
  <ul class="nav nav-pills justify-content-end">
    <li class="nav-item ">
      <a class="navbar-brand nav-link active" href="{% url 'dashboard' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'ranking' %}">Ranking</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'bets' %}">Minhas Apostas</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'add_credit' %}">Adicionar Crédito</a>
    </li>
    {% if user.is_superuser %} <!-- Se for um administrador do sistema mostra esta opção-->
      <li class="nav-item">
        <a class="navbar-brand nav-link" href="{% url 'admin_register_result' %}">Registrar Resultado da Partida</a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'logout' %}">Sair</a>
    </li>
</ul>

<h1 class="display-3">Painel do Apostador</h1>
<p>
    Seja bem-vindo <b> {{ user.first_name }} {{ user.last_name }} </b> seu SALDO atual é de : <b>R$ {{ apostador_credito.credito }}  </b>.
    {% include 'parciais/_messages.html' %}
</p>
<div id="container">
 
<table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome do Bolão</th>
          <th>Estádio</th>
          <th>Data/Hora da Partida</th>
          <th>Gols Desafiante</th>
          <th>Gols Visitante</th>
          <th>Acão</th>
        </tr>
      </thead>
      <tbody>
        
        {% for bolao in boloes %}
         <form method="POST" action="{% url 'dashboard' %}">
              {% csrf_token %}
              <input type="hidden" id="apostador" name="apostador" value="{{ user.id }}" />
              <input type="hidden" id="bolao" name="bolao" value="{{ bolao.id }}" />
              <tr>
                <td>{{ bolao.id }}</td>
                <td>{{ bolao.nome }}</td>
                <td>{{ bolao.partida.estadio}}</td>
                <td> <b> Início: </b> {{ bolao.partida.data_hora_inicio }} </br>
                     <b> Final: </b> {{ bolao.partida.data_hora_fim }}
                </td>
                <td> 
                  <div class="form-group">
                    <label>{{ bolao.partida.selecao_desafiante.nome }}</label>
                    <input type="number" name="gols_desaf" required value="" min="0" max="15" maxlength="2" class="form-control">
                  </div>
                </td>
                <td> 
                  <div class="form-group">
                    <label>{{ bolao.partida.selecao_visitante.nome }}</label>
                    <input type="number" name="gols_visit" required value="" min="0" max="15" maxlength="2" class="form-control">
                  </div>
                </td>
                <td> 
                  </br><button type="submit" class="btn btn-sm btn-danger">APOSTAR</button>
                </td>
              </tr>
        </form>
        {% endfor %}

      </tbody>
    </table>

</div>

{% endblock %}

bolao_app/templates/bolao_app/dashboard_add_credit.html
<style>
  #container {
      border-radius: 10px;
      background-color: rgba(255, 255, 255, 0.7);
      padding : 20px;
      }

</style>

{% extends 'base.html' %}
{% block  titulo%} Adicionar crédito | {% endblock  %}

{% block conteudo %}
  <!-- Navigation -->
  <ul class="nav nav-pills justify-content-end">
    <li class="nav-item ">
      <a class="navbar-brand nav-link " href="{% url 'dashboard' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'ranking' %}">Ranking</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'bets' %}">Minhas Apostas</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link active" href="{% url 'add_credit' %}">Adicionar Crédito</a>
    </li>
    {% if user.is_superuser %} <!-- Se for um administrador do sistema mostra esta opção-->
      <li class="nav-item">
        <a class="navbar-brand nav-link" href="{% url 'admin_register_result' %}">Registrar Resultado da Partida</a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'logout' %}">Sair</a>
    </li>
</ul>

<h1 class="display-3">Adicionar Créditos</h1>
<p>
    Seja bem-vindo <b> {{ user.first_name }} {{ user.last_name }}
</p>
{% include 'parciais/_messages.html' %}
<div id="container">
  <form method="POST" action="{% url 'add_credit' %}">
        {% csrf_token %}
      <div class="form-group">
        <label>Crédito atual</label>
        <input type="text" disabled="" name="credito_atual" value="{{ apostador_credito.credito }}" class="form-control">
      </div>
      <div class="form-group">
        <label>Infome o valor que deseja acicionar em céditos</label>
        <input type="number" name="valor_adicional" required value="" min="0" max="100" step="0.01" class="form-control">
      </div>
      <button type="submit" class="btn btn-primary">Adicionar Crédito</button>
  </form>
</div>
{% endblock %}

bolao_app/templates/bolao_app/dashboard_admin_register_result.html
<style>
  #container {
      border-radius: 10px;
      background-color: rgba(255, 255, 255, 0.7);
      padding : 20px;
      }

</style>

{% extends 'base.html' %}
{% block  titulo%} Registra resultado da partida | {% endblock  %}

{% block conteudo %}
  <!-- Navigation -->
  <ul class="nav nav-pills justify-content-end">
    <li class="nav-item ">
      <a class="navbar-brand nav-link " href="{% url 'dashboard' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'ranking' %}">Ranking</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'bets' %}">Minhas Apostas</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'add_credit' %}">Adicionar Crédito</a>
    </li>
    {% if user.is_superuser %} <!-- Se for um administrador do sistema mostra esta opção-->
      <li class="nav-item">
        <a class="navbar-brand nav-link active" href="{% url 'admin_register_result' %}">Registrar Resultado da Partida</a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'logout' %}">Sair</a>
    </li>
</ul>

<h1 class="display-3">Registar Resultado das Partidas (Admin)</h1>
<p>
    Seja bem-vindo <b> {{ user.first_name }} {{ user.last_name }}
</p>
{% include 'parciais/_messages.html' %}

<div id="container">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome do Bolão</th>
          <th>Estádio</th>
          <th>Data/Hora da Partida</th>
          <th>Resul. Final: Gols do Desaf.</th>
          <th>esul. Final: Gols do Visit.</th>
          <th>Registrar Resultado</th>
        </tr>
      </thead>
      <tbody>
        
        {% for partida in partidas %} <!-- partidas -->
         <form method="POST" action="{% url 'admin_register_result' %}">
              {% csrf_token %}
              <input type="hidden" id="id_partida" name="id_partida" value="{{ partida.id }}" />
              <input type="hidden" id="id_bolao" name="id_bolao" value="{{ partida.id }}" /> <!-- rever -->
              <tr>
                <td>{{ partida.id }}</td>
                <td>{{ partida.bolao }}</td>
                <td>{{ partida.estadio }}</td>
                <td> <b> Início: </b> {{ partida.data_hora_inicio }} </br>
                     <b> Final: </b> {{ partida.data_hora_fim }}
                </td>
                <td> 
                  <div class="form-group">
                    <label>{{ partida.selecao_desafiante.nome }}</label>
                    <input type="number" name="gols_desaf" required value="" min="0" max="15" maxlength="2" class="form-control">
                  </div>
                </td>
                <td> 
                  <div class="form-group">
                    <label>{{ partida.selecao_visitante.nome }}</label>
                    <input type="number" name="gols_visit" required value="" min="0" max="15" maxlength="2" class="form-control">
                  </div>
                </td>
                <td> 
                  </br><button type="submit" class="btn btn-sm btn-danger">REGISTRAR</button>
                </td>
              </tr>
        </form>
        {% endfor %}

      </tbody>
    </table>
</div>
{% endblock %}

bolao_app/templates/bolao_app/dashboard_bets.html
<style>
  #container {
      border-radius: 10px;
      background-color: rgba(255, 255, 255, 0.7);
      padding : 20px;
      }

</style>

{% extends 'base.html' %}
{% block  titulo%} Lista de minhas apostas | {% endblock  %}

{% block conteudo %}
  <!-- Navigation -->
  <ul class="nav nav-pills justify-content-end">
    <li class="nav-item ">
      <a class="navbar-brand nav-link " href="{% url 'dashboard' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'ranking' %}">Ranking</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link active" href="{% url 'bets' %}">Minhas Apostas</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'add_credit' %}">Adicionar Crédito</a>
    </li>
    {% if user.is_superuser %} <!-- Se for um administrador do sistema mostra esta opção-->
      <li class="nav-item">
        <a class="navbar-brand nav-link" href="{% url 'admin_register_result' %}">Registrar Resultado da Partida</a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'logout' %}">Sair</a>
    </li>
</ul>

<h1 class="display-3">Minhas Apostas</h1>
<p>
    Seja bem-vindo <b> {{ user.first_name }} {{ user.last_name }}
</p>
<div id="container">
  
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome do Bolão</th>
          <th>Estádio</th>
          <th>Data/Hora da Partida</th>
          <th>Palpite da Aposta</th>
          <th>Resultado da Partida</th>
        </tr>
      </thead>
      <tbody>
        
        {% for aposta in apostas %} <!-- apostas e não biolao-->
              <tr>
                <td>{{ aposta.bolao.id }}</td>
                <td>{{ aposta.bolao }}</td>
                <td>{{ aposta.bolao.partida.estadio}}</td>
                <td> <b> Início: </b> {{ aposta.bolao.partida.data_hora_inicio }} </br>
                     <b> Final: </b> {{ aposta.bolao.partida.data_hora_fim }}
                </td>
                <td> 
                   {{ aposta.bolao.partida.selecao_desafiante }} {{ aposta.qtd_gols_desafiante }} x 
                   {{ aposta.qtd_gols_visitante }} {{ aposta.bolao.partida.selecao_visitante}} {% comment %} palpite da aposta {% endcomment %}
                </td>
                <td> 
                  {{ aposta.bolao.partida.selecao_desafiante }} {{ aposta.bolao.partida.gols_desafiante }} x 
                   {{ aposta.bolao.partida.gols_visitante }} {{ aposta.bolao.partida.selecao_visitante}} {% comment %} resultado da partida {% endcomment %}
                  
                </td>
              </tr>
        {% endfor %}

      </tbody>
    </table>

</div>
{% comment %} 
<!-- botão do modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ExemploModalCentralizado">Abrir</button>
<!-- Modal -->
<div class="modal fade" id="ExemploModalCentralizado" tabindex="-1" role="dialog" aria-labelledby="TituloModalCentralizado" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="TituloModalCentralizado">Título do modal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-primary">Salvar mudanças</button>
      </div>
    </div>
  </div>
</div>
 {% endcomment %}
{% endblock %}

bolao_app/templates/bolao_app/dashboard_bets_result.html
<style>
  #container {
      border-radius: 10px;
      background-color: rgba(255, 255, 255, 0.7);
      padding : 20px;
      }

</style>

{% extends 'base.html' %}
{% block  titulo%} Resultado de minhas apostas | {% endblock  %}


{% block conteudo %}
<h1 class="display-3">Painel do Apostador</h1>
<div id="container">
  
</div>
{% endblock %}

bolao_app/templates/bolao_app/dashboard_ranking.html
<style>
  #container {
      border-radius: 10px;
      background-color: rgba(255, 255, 255, 0.7);
      padding : 20px;
      }

</style>

{% extends 'base.html' %}
{% block  titulo%} Ranking dos Apostadores | {% endblock  %}

{% block conteudo %}
  <!-- Navigation -->
  <ul class="nav nav-pills justify-content-end">
    <li class="nav-item ">
      <a class="navbar-brand nav-link " href="{% url 'dashboard' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link active" href="{% url 'ranking' %}">Ranking</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'bets' %}">Minhas Apostas</a>
    </li>
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'add_credit' %}">Adicionar Crédito</a>
    </li>
    {% if user.is_superuser %} <!-- Se for um administrador do sistema mostra esta opção-->
      <li class="nav-item">
        <a class="navbar-brand nav-link" href="{% url 'admin_register_result' %}">Registrar Resultado da Partida</a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="navbar-brand nav-link" href="{% url 'logout' %}">Sair</a>
    </li>
</ul>


<h1 class="display-3">Ranking dos Apostadores</h1>
<p>
    Seja bem-vindo <b> {{ user.first_name }} {{ user.last_name }}
</p>
<div id="container">

        <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Qtd. de Vitórias</th>
          <th>Valor Ganho em Premiações</th>
      </thead>
      <tbody>
        
        {% for usuario in usuarios %} <!-- apostas e não biolao-->
              <tr>
                <td>{{ usuario.id }}</td>
                <td>{{ usuario.username }}</td>
                <td>{{ usuario.apostadorusuario.qtd_vitorias }}</td>
                <td>{{ usuario.apostadorusuario.premiacao_ganha  }}</td>
              </tr>
        {% endfor %}

      </tbody>
    </table>

</div>

{% endblock %}

bolao_app/templates/bolao_app/landingpage.html
{% extends 'base.html' %}

{%block conteudo%}
    <h1 class="mt-5"> Bolão da Sorte </h1>
    
    <div class="jumbotron">
        <h1 class="display-4">Seja bem vindo ao Bolão da Sorte!</h1>
        <p class="lead">Aqui você pode fazer suas apostas com segurança e confiabilidade, faça seu cadastro e comece agora com suas apostas.</p>
        <hr class="my-4">
        <p>Faça seu login ou cadastre-se para ter acesso ao painel de apostas.</p>
        <a class="btn btn-danger btn-lg btn-block" href="{% url 'login' %}" role="button">Login</a>
        <a class="btn btn-primary btn-lg btn-block" href="{% url 'register' %}" role="button">Cadastra-se</a>
    </div>
    

{%endblock%}

bolao_app/templates/bolao_app/login.html
<style>
  #container {
      border-radius: 10px;
      background-color: rgba(255, 255, 255, 0.7);
      padding : 20px;
      }

</style>

{% extends 'base.html' %}
{% block  titulo%} Login | {% endblock  %}
{% block conteudo %}

  <h1 class="display-3">Login</h1>

  {% if not user.is_authenticated  %} <!-- Verifica se o usurario esta logado -->  
    <div id="container">
          <form method="POST" action="{% url 'login' %}">
              {% include 'parciais/_messages.html' %}
              {% csrf_token %}
            <div class="form-group">
              <label>Usuário</label>
              <input type="text" name="usuario" value="{{request.POST.usuario}}" class="form-control">
            </div>
            <div class="form-group">
              <label>Senha</label>
              <input type="password" name="senha" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Entrar</button>
          </form>
    </div>
  {% else %}
    <p> 
      Voçê já está logado como <b> {{ user.first_name }} {{ user.last_name }} </b>, 
      <a href="{% url 'logout' %}"> clique aqui </a> se desejar <b>sair da aplicação!</b> 
    </p>
  {% endif %}
{% endblock %}